"""Single source of truth for persistent profile fields and memory reduction."""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Literal

ValueKind = Literal["scalar", "list"]
ReducerKind = Literal["replace_one", "unique_set", "opposing_set", "bounded_event", "lifecycle"]
MemoryScope = Literal["user", "agent", "session"]
LifecycleKind = Literal["persistent", "temporal", "session"]


@dataclass(frozen=True, slots=True)
class MemoryField:
    field_code: str
    target: str
    path: str
    display_name: str
    category: str
    value_kind: ValueKind
    reducer: ReducerKind
    scope: MemoryScope
    lifecycle: LifecycleKind
    max_items: int = 1
    conflict_group: str = ""
    polarity: str = "neutral"

    def public(self) -> dict[str, object]:
        return asdict(self)


def _field(
    field_code: str,
    target: str,
    path: str,
    display_name: str,
    category: str,
    value_kind: ValueKind,
    reducer: ReducerKind,
    scope: MemoryScope,
    lifecycle: LifecycleKind,
    max_items: int = 1,
    conflict_group: str = "",
    polarity: str = "neutral",
) -> MemoryField:
    return MemoryField(
        field_code=field_code,
        target=target,
        path=path,
        display_name=display_name,
        category=category,
        value_kind=value_kind,
        reducer=reducer,
        scope=scope,
        lifecycle=lifecycle,
        max_items=max_items,
        conflict_group=conflict_group,
        polarity=polarity,
    )


FIELDS = (
    _field(
        "user.identity.name",
        "user_profile",
        "/identity/preferred_name",
        "常用称呼",
        "身份",
        "scalar",
        "replace_one",
        "user",
        "persistent",
    ),
    _field(
        "user.identity.occupation",
        "user_profile",
        "/identity/occupation",
        "职业",
        "身份",
        "scalar",
        "replace_one",
        "user",
        "persistent",
    ),
    _field(
        "user.communication.tone",
        "user_profile",
        "/communication_preferences/preferred_tone",
        "偏好语气",
        "交流偏好",
        "scalar",
        "replace_one",
        "user",
        "persistent",
    ),
    _field(
        "user.communication.length",
        "user_profile",
        "/communication_preferences/response_length",
        "回复长度",
        "交流偏好",
        "scalar",
        "replace_one",
        "user",
        "persistent",
    ),
    _field(
        "user.communication.depth",
        "user_profile",
        "/communication_preferences/explanation_depth",
        "解释深度",
        "交流偏好",
        "scalar",
        "replace_one",
        "user",
        "persistent",
    ),
    _field(
        "user.communication.names",
        "user_profile",
        "/communication_preferences/preferred_names",
        "喜欢的称呼",
        "交流偏好",
        "list",
        "unique_set",
        "user",
        "persistent",
        20,
    ),
    _field(
        "user.communication.disliked_expressions",
        "user_profile",
        "/communication_preferences/disliked_expressions",
        "不喜欢的表达",
        "交流偏好",
        "list",
        "unique_set",
        "user",
        "persistent",
        50,
    ),
    _field(
        "user.preference.likes",
        "user_profile",
        "/stable_preferences/likes",
        "喜欢",
        "偏好",
        "list",
        "opposing_set",
        "user",
        "persistent",
        100,
        "user.preference",
        "like",
    ),
    _field(
        "user.preference.dislikes",
        "user_profile",
        "/stable_preferences/dislikes",
        "不喜欢",
        "偏好",
        "list",
        "opposing_set",
        "user",
        "persistent",
        100,
        "user.preference",
        "dislike",
    ),
    _field(
        "user.preference.interests",
        "user_profile",
        "/stable_preferences/interests",
        "兴趣",
        "偏好",
        "list",
        "unique_set",
        "user",
        "persistent",
        100,
    ),
    _field(
        "user.preference.habits",
        "user_profile",
        "/stable_preferences/habits",
        "习惯",
        "偏好",
        "list",
        "unique_set",
        "user",
        "persistent",
        100,
    ),
    _field(
        "user.background.experiences",
        "user_profile",
        "/background/important_experiences",
        "重要经历",
        "经历",
        "list",
        "bounded_event",
        "user",
        "persistent",
        50,
    ),
    _field(
        "user.behavior.apply",
        "user_profile",
        "/behavior_requirements/always_apply",
        "始终遵守",
        "行为边界",
        "list",
        "opposing_set",
        "user",
        "persistent",
        50,
        "user.behavior.instruction",
        "apply",
    ),
    _field(
        "user.behavior.avoid",
        "user_profile",
        "/behavior_requirements/avoid",
        "避免行为",
        "行为边界",
        "list",
        "opposing_set",
        "user",
        "persistent",
        50,
        "user.behavior.instruction",
        "avoid",
    ),
    _field(
        "user.behavior.boundaries",
        "user_profile",
        "/behavior_requirements/hard_boundaries",
        "硬性边界",
        "行为边界",
        "list",
        "unique_set",
        "user",
        "persistent",
        50,
    ),
    _field(
        "agent.identity.name",
        "ai_profile",
        "/identity/name",
        "角色名称",
        "角色身份",
        "scalar",
        "replace_one",
        "agent",
        "persistent",
    ),
    _field(
        "agent.identity.description",
        "ai_profile",
        "/identity/self_description",
        "角色自述",
        "角色身份",
        "scalar",
        "replace_one",
        "agent",
        "persistent",
    ),
    _field(
        "agent.identity.relationship",
        "ai_profile",
        "/identity/relationship_to_user",
        "与用户关系",
        "角色身份",
        "scalar",
        "replace_one",
        "agent",
        "persistent",
    ),
    _field(
        "agent.personality.traits",
        "ai_profile",
        "/personality/core_traits",
        "核心性格",
        "角色性格",
        "list",
        "unique_set",
        "agent",
        "persistent",
        30,
    ),
    _field(
        "agent.personality.speech",
        "ai_profile",
        "/personality/speech_style",
        "表达风格",
        "角色性格",
        "list",
        "unique_set",
        "agent",
        "persistent",
        30,
    ),
    _field(
        "agent.relationship.definition",
        "ai_profile",
        "/relationship_rules/relationship_definition",
        "关系定义",
        "关系规则",
        "scalar",
        "replace_one",
        "agent",
        "persistent",
    ),
    _field(
        "agent.relationship.preferred",
        "ai_profile",
        "/relationship_rules/preferred_interactions",
        "偏好互动",
        "关系规则",
        "list",
        "unique_set",
        "agent",
        "persistent",
        50,
    ),
    _field(
        "agent.relationship.conflict",
        "ai_profile",
        "/relationship_rules/conflict_behavior",
        "冲突处理",
        "关系规则",
        "list",
        "unique_set",
        "agent",
        "persistent",
        30,
    ),
    _field(
        "agent.relationship.repair",
        "ai_profile",
        "/relationship_rules/repair_behavior",
        "关系修复",
        "关系规则",
        "list",
        "unique_set",
        "agent",
        "persistent",
        30,
    ),
    _field(
        "agent.behavior.apply",
        "ai_profile",
        "/behavior_rules/always_apply",
        "始终执行",
        "角色行为",
        "list",
        "opposing_set",
        "agent",
        "persistent",
        50,
        "agent.behavior.instruction",
        "apply",
    ),
    _field(
        "agent.behavior.contextual",
        "ai_profile",
        "/behavior_rules/contextual_rules",
        "情境规则",
        "角色行为",
        "list",
        "unique_set",
        "agent",
        "persistent",
        50,
    ),
    _field(
        "agent.behavior.avoid",
        "ai_profile",
        "/behavior_rules/avoid",
        "避免行为",
        "角色行为",
        "list",
        "opposing_set",
        "agent",
        "persistent",
        50,
        "agent.behavior.instruction",
        "avoid",
    ),
    _field(
        "agent.behavior.boundaries",
        "ai_profile",
        "/behavior_rules/hard_boundaries",
        "角色边界",
        "角色行为",
        "list",
        "unique_set",
        "agent",
        "persistent",
        50,
    ),
    _field(
        "agent.continuity.experiences",
        "ai_profile",
        "/continuity/important_shared_experiences",
        "共同经历",
        "关系延续",
        "list",
        "bounded_event",
        "agent",
        "persistent",
        50,
    ),
    _field(
        "agent.continuity.attitudes",
        "ai_profile",
        "/continuity/persistent_attitudes",
        "持续态度",
        "关系延续",
        "list",
        "unique_set",
        "agent",
        "persistent",
        30,
    ),
    _field(
        "agent.continuity.goals",
        "ai_profile",
        "/continuity/long_term_goals",
        "长期目标",
        "关系延续",
        "list",
        "unique_set",
        "agent",
        "persistent",
        30,
    ),
    _field(
        "runtime.relationship.stage",
        "runtime_state",
        "/relationship_state/current_stage",
        "当前关系阶段",
        "当前关系",
        "scalar",
        "replace_one",
        "session",
        "temporal",
    ),
    _field(
        "runtime.relationship.tone",
        "runtime_state",
        "/relationship_state/current_tone",
        "当前关系氛围",
        "当前关系",
        "scalar",
        "replace_one",
        "session",
        "temporal",
    ),
    _field(
        "runtime.relationship.conflicts",
        "runtime_state",
        "/relationship_state/recent_conflicts",
        "近期冲突",
        "当前关系",
        "list",
        "bounded_event",
        "session",
        "temporal",
        20,
    ),
    _field(
        "runtime.relationship.unresolved",
        "runtime_state",
        "/relationship_state/unresolved_issues",
        "未解决事项",
        "当前关系",
        "list",
        "lifecycle",
        "session",
        "temporal",
        30,
    ),
    _field(
        "runtime.relationship.positive_events",
        "runtime_state",
        "/relationship_state/recent_positive_events",
        "近期积极事件",
        "当前关系",
        "list",
        "bounded_event",
        "session",
        "temporal",
        30,
    ),
    _field(
        "runtime.user.goal",
        "runtime_state",
        "/user_state/current_goal",
        "当前目标",
        "用户当前状态",
        "scalar",
        "replace_one",
        "session",
        "temporal",
    ),
    _field(
        "runtime.user.task",
        "runtime_state",
        "/user_state/current_task",
        "当前任务",
        "用户当前状态",
        "scalar",
        "replace_one",
        "session",
        "temporal",
    ),
    _field(
        "runtime.user.topic",
        "runtime_state",
        "/user_state/current_topic",
        "当前话题",
        "用户当前状态",
        "scalar",
        "replace_one",
        "session",
        "session",
    ),
    _field(
        "runtime.user.temporary_preferences",
        "runtime_state",
        "/user_state/temporary_preferences",
        "临时偏好",
        "用户当前状态",
        "list",
        "unique_set",
        "session",
        "session",
        20,
    ),
    _field(
        "runtime.user.emotional_cues",
        "runtime_state",
        "/user_state/current_emotional_cues",
        "当前情绪线索",
        "用户当前状态",
        "list",
        "bounded_event",
        "session",
        "session",
        10,
    ),
    _field(
        "runtime.agent.pending_responses",
        "runtime_state",
        "/ai_state/pending_responses",
        "待回应事项",
        "AI 当前状态",
        "list",
        "lifecycle",
        "session",
        "session",
        20,
    ),
    _field(
        "runtime.agent.emotional_cues",
        "runtime_state",
        "/ai_state/current_emotional_cues",
        "AI 当前情绪线索",
        "AI 当前状态",
        "list",
        "bounded_event",
        "agent",
        "session",
        10,
    ),
    _field(
        "runtime.agent.intentions",
        "runtime_state",
        "/ai_state/current_intentions",
        "AI 当前意图",
        "AI 当前状态",
        "list",
        "lifecycle",
        "agent",
        "session",
        20,
    ),
    _field(
        "runtime.session.summary",
        "runtime_state",
        "/session_state/session_summary",
        "会话摘要",
        "会话状态",
        "scalar",
        "replace_one",
        "session",
        "session",
    ),
    _field(
        "runtime.session.questions",
        "runtime_state",
        "/session_state/open_questions",
        "开放问题",
        "会话状态",
        "list",
        "lifecycle",
        "session",
        "session",
        30,
    ),
    _field(
        "runtime.session.actions",
        "runtime_state",
        "/session_state/pending_actions",
        "待办事项",
        "会话状态",
        "list",
        "lifecycle",
        "session",
        "session",
        30,
    ),
    _field(
        "runtime.session.entities",
        "runtime_state",
        "/session_state/active_entities",
        "当前实体",
        "会话状态",
        "list",
        "unique_set",
        "session",
        "session",
        50,
    ),
)


class MemoryRegistry:
    def __init__(self, fields: tuple[MemoryField, ...] = FIELDS) -> None:
        self.fields = fields
        self._by_location = {(field.target, field.path): field for field in fields}
        self._by_code = {field.field_code: field for field in fields}
        if len(self._by_location) != len(fields) or len(self._by_code) != len(fields):
            raise ValueError("memory registry contains duplicate path or field_code")

    @staticmethod
    def base_path(path: str) -> str:
        parts = path.rstrip("/").split("/")
        if parts and (parts[-1] == "-" or parts[-1].isdigit()):
            return "/".join(parts[:-1]) or "/"
        return path

    def resolve(self, target: str, path: str) -> MemoryField | None:
        return self._by_location.get((target, self.base_path(path)))

    def by_code(self, field_code: str) -> MemoryField | None:
        return self._by_code.get(field_code)

    def public(self) -> list[dict[str, object]]:
        return [field.public() for field in self.fields]


DEFAULT_MEMORY_REGISTRY = MemoryRegistry()
